import Foundation

/// Decodes the bundled SF sample network (`Resources/SFSampleNetwork.json`,
/// generated by `Scripts/generate_sample_network.py`) into raw edges and runs
/// them through the same `NetworkGraphBuilder` pipeline as live ingestion.
/// Node elevations are baked into the file, so no elevation provider is
/// needed on this path.
struct SampleNetworkLoader {
    struct File: Decodable {
        struct Node: Decodable {
            let id: String
            let latitude: Double
            let longitude: Double
            let elevationMeters: Double
        }

        struct Edge: Decodable {
            let fromNode: String
            let toNode: String
            let streetName: String
            let facilityType: String
            let protectionLevel: String
            let roadClass: String
            let surfaceType: String
            let oneWay: Bool
            let confidence: Double
        }

        let nodes: [Node]
        let edges: [Edge]
    }

    var bundle: Bundle = .main
    var builder = NetworkGraphBuilder()

    func loadGraph() async throws -> RouteGraph {
        guard let url = bundle.url(forResource: "SFSampleNetwork", withExtension: "json") else {
            throw GeospatialDataError.sampleDataMissing
        }
        return try await loadGraph(from: url)
    }

    func loadGraph(from url: URL) async throws -> RouteGraph {
        let file = try JSONDecoder().decode(File.self, from: Data(contentsOf: url))
        let coordinatesByID = Dictionary(uniqueKeysWithValues: file.nodes.map {
            ($0.id, RouteCoordinate(
                latitude: $0.latitude,
                longitude: $0.longitude,
                elevation: $0.elevationMeters
            ))
        })

        let rawEdges: [RawNetworkEdge] = file.edges.compactMap { edge in
            guard let from = coordinatesByID[edge.fromNode],
                  let to = coordinatesByID[edge.toNode] else { return nil }
            return RawNetworkEdge(
                geometry: [from, to],
                streetName: edge.streetName,
                facilityType: BikeFacilityType(rawValue: edge.facilityType) ?? .unknown,
                protectionLevel: ProtectionLevel(rawValue: edge.protectionLevel) ?? .unknown,
                roadClass: RoadClass(rawValue: edge.roadClass) ?? .unknown,
                surfaceType: SurfaceType(rawValue: edge.surfaceType) ?? .unknown,
                oneWay: edge.oneWay,
                attributeConfidence: edge.confidence
            )
        }

        return try await builder.buildGraph(from: rawEdges, elevationProvider: nil)
    }
}
